# Joshua Wyckoff
# Problem 2: Even Fibonacci Numbers
# Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

a = 1
b = 2
c = 0
sum = 2
# Test Case: Max = 100, should return 44 (2 + 8 + 34)
# max = 100
max = 4000000

# Loops through calculation next Fibanacci Number c until c exceeds the max value. 
# If c exceeds max, the loop breaks.
# Otherwise, a is set to b, b is set to c, and if c is even, it is added to the sum.
while (True):
    c = a + b
    if (c > max): break
    a = b
    b = c
    if (c % 2 == 0):
        sum += c

print(sum)